### PR TITLE
Configuration service in Kind

### PR DESCRIPTION
**Pull request by plasorak**
With this PR and the changes in them, one gets 3 pods deployed when using `SERVICES="daqconfig"`
 - 1 pod is a StatefulSet containing a MongoDB image, which stores data persistently in pocket/share, listening on port 31007.
 - 1 pod is a configuration service (https://github.com/DUNE-DAQ/microservices/pull/1) that on port 31012
 - 1 pod running a read-only mongo express instance, at 31011, for quick visualisation.

I haven't tried on the real cluster (i.e. outside `kind`).

### CODE REVIEW

**Comment by bonnieking** [comment]
`source_me_python_venv.sh` exits if HTTP_PROXY isn't set, but we don't need an http proxy in all environments.

**Comment by plasorak** [comment]
Yeah, you're right, we probably don't need this script in the first place, this was a relatively hacky way to check if the service was accessible.

**Comment by bonnieking** [comment]
I think it's not needed, plus it has a password in it.

**Comment by plasorak** [comment]
Ouch, yes, very bad, sorry about that.

**Comment by bonnieking** [comment]
Works for me!

**Pull request merged**
